Async/await
mxcl/PromiseKit pull request #1291
Opened 2022-07-14 11:55 UTC by RomanPodymov

Hello.
Thank you for PromiseKit.
Added compatibility with async/await.

2022-07-24 12:18 UTC, mxcl approved these changes

2022-07-24 12:19 UTC, mxcl requested changes
Needs to pass CI, our strategy with these typically is to add the `#if` inside the test bodies so that they pass because they have no content.

2022-07-24 21:10 UTC, RomanPodymov commented
> Needs to pass CI, our strategy with these typically is to add the `#if` inside the test bodies so that they pass because they have no content.

Fixed.

2022-07-25 15:11 UTC, mxcl approved these changes

2022-07-25 15:12 UTC, merged

2022-07-25 20:39 UTC, mxcl commented
v6.18.0 released. Thanks for the contribution.

2022-08-10 01:20 UTC, mxcl commented
K possibly this is just we now require a newer Xcode https://stackoverflow.com/questions/69284960/ios-concurrency-is-only-available-in-ios-15-0-0-or-newer-in-protocol